name: 'build'
on:
  workflow_dispatch:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.4.4"
      - run: lua test.lua
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@master
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: class
          path: |
            class.lua
            LICENSE.md
            README.md
      - uses: actions/download-artifact@v2