name: 'Distribute Artifact'
on:
  workflow_dispatch:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          architecture: 'x64'
      - uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.4"
      - run: python ./tools/test.py
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          architecture: 'x64'
      - run: python ./tools/distribution.py
      - uses: actions/upload-artifact@v2
        with:
          path: class.zip
      - uses: actions/download-artifact@v2
